"""create_initial_state() parity with the JS engine.

Python ports the leaf function shared/scheduler/scheduler.js::createInitialState
so GET /api/scheduler/state can return 200 + a fresh initial state on first
launch (matching Node) instead of 404. createInitialState is a true leaf —
it pulls no other engine code, and migrateLoadedState is a no-op on its
already-canonical output (proven by the fixture validating) — so porting it
opens no further door.

Parity is enforced against the JS-frozen fixture (regenerated by
scripts/freeze-contracts.mjs) modulo the two dynamically-computed block date
fields, which depend on "today".
"""

import datetime
import json
from pathlib import Path

from backend_py.contracts import validate
from backend_py.initial_state import create_initial_state

FIXTURES = Path(__file__).resolve().parent / "fixtures"


def _strip_dynamic_dates(state):
    """Return a copy with the active block's computed dates removed."""
    clone = json.loads(json.dumps(state))
    for block in clone["serviceBlocks"]:
        block.pop("startDate", None)
        block.pop("endDate", None)
    return clone


def test_initial_state_is_valid_v1():
    assert validate("scheduler-state.v1", create_initial_state()) == []


def test_initial_state_matches_js_fixture_modulo_dates():
    py = create_initial_state()
    js = json.loads((FIXTURES / "initial-state.json").read_text(encoding="utf-8"))
    assert _strip_dynamic_dates(py) == _strip_dynamic_dates(js)


def test_initial_state_block_dates_are_today_and_plus_27():
    state = create_initial_state()
    block = state["serviceBlocks"][0]
    today = datetime.date.today()
    assert block["startDate"] == today.isoformat()
    assert block["endDate"] == (today + datetime.timedelta(days=27)).isoformat()


def test_initial_state_is_non_authoritative():
    # Must not look authoritative, or the frontend would adopt it over real
    # localStorage data (src/storage.js::isBackendStateAuthoritative).
    state = create_initial_state()
    assert state["rotators"] == []
    assert state["inpatientAssignments"] == []
    assert state["outpatientSessions"] == []
    assert len(state["serviceBlocks"]) == 1
