"""Golden-vector parity harness for the JS->Python engine port.

Loads the vectors dumped from the real JS functions
(contracts/golden/*.json, regenerated by `node scripts/dump-golden.mjs`) and
asserts the Python port produces identical output. This is how port parity is
proven: one small harness covers every ported function's real test inputs, so
adding a function to the port means adding its vectors, not hand-mirroring
assertions that drift from the JS source.

Module-private JS helpers that can't be exported for vectoring
(addDaysToIso via extendBlockEnd is covered above; daysBetween) get direct
unit tests here.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from backend_py.domain import calendar_utils as cal
from backend_py.domain.assignments import apply_range_assignment, schedule_outpatient_session
from backend_py.domain.draft import apply_preassignments, generate_draft, get_rotator_segment_phase, propose_schedule
from backend_py.domain.reports import generate_daily_report

GOLDEN_DIR = Path(__file__).resolve().parent.parent.parent / "contracts" / "golden"

# Map each vectored function name to its Python implementation.
_PORTED = {
    "weekdayName": cal.weekday_name,
    "dateRange": cal.date_range,
    "extendBlockEnd": cal.extend_block_end,
}


def _load_cases():
    data = json.loads((GOLDEN_DIR / "calendar.json").read_text(encoding="utf-8"))
    cases = []
    for fn_name, vectors in data["cases"].items():
        for i, vec in enumerate(vectors):
            cases.append(
                pytest.param(
                    fn_name, vec["input"], vec["output"], id=f"{fn_name}[{i}]"
                )
            )
    return cases


@pytest.mark.parametrize("fn_name,inputs,expected", _load_cases())
def test_calendar_golden_parity(fn_name, inputs, expected):
    fn = _PORTED[fn_name]
    assert fn(*inputs) == expected


# --- direct tests for helpers not reachable as JS exports -------------------


@pytest.mark.parametrize(
    "from_str,to_str,expected",
    [
        ("2026-07-01", "2026-07-01", 0),
        ("2026-07-01", "2026-07-16", 15),  # methodist day-14 boundary math
        ("2026-07-16", "2026-07-01", -15),
        ("2026-05-20", "2026-06-03", 14),  # spec 9.1 worked example: OP->IP flip
        ("2026-02-27", "2026-03-01", 2),   # non-leap month boundary
        ("2028-02-28", "2028-03-01", 2),   # across leap day (Feb 29 2028)
        ("2026-03-07", "2026-03-09", 2),   # across US spring-forward (no drift)
    ],
)
def test_days_between(from_str, to_str, expected):
    assert cal.days_between(from_str, to_str) == expected


@pytest.mark.parametrize("bad", [(None, "2026-07-01"), ("2026-07-01", None), (None, None)])
def test_days_between_missing_returns_none(bad):
    assert cal.days_between(*bad) is None


def test_add_days_to_iso_direct():
    assert cal.add_days_to_iso("2026-07-30", 7) == "2026-08-06"
    assert cal.add_days_to_iso("2026-01-01", -1) == "2025-12-31"
    assert cal.add_days_to_iso("2028-02-28", 1) == "2028-02-29"  # leap day exists


def test_get_rotator_segment_phase_stops_at_first_matching_segment():
    rotator = {
        "segments": [
            {"start": "2026-05-04", "end": "2026-05-10"},
            {"start": "2026-05-04", "end": "2026-05-10", "defaultPhase": "inpatient"},
        ]
    }

    assert get_rotator_segment_phase(rotator, "2026-05-05") is None


def _load_draft_cases():
    data = json.loads((GOLDEN_DIR / "draft-fair-fill.json").read_text(encoding="utf-8"))
    return [
        pytest.param(vec["input"][0], vec["input"][1], vec["output"], id=vec["name"])
        for vec in data["cases"]
    ]


@pytest.mark.parametrize("state,block,expected", _load_draft_cases())
def test_propose_schedule_golden_parity(state, block, expected):
    assert propose_schedule(state, block) == expected


def _load_full_draft_cases():
    data = json.loads((GOLDEN_DIR / "draft-full.json").read_text(encoding="utf-8"))
    return [
        pytest.param(vec["input"][0], vec["input"][1], vec["output"], id=vec["name"])
        for vec in data["cases"]
    ]


@pytest.mark.parametrize("state,block,expected", _load_full_draft_cases())
def test_generate_draft_golden_parity(state, block, expected):
    assert generate_draft(state, block) == expected


def _load_preassignment_cases():
    data = json.loads((GOLDEN_DIR / "preassignments.json").read_text(encoding="utf-8"))
    return [
        pytest.param(vec["input"][0], vec["input"][1], vec["output"], id=vec["name"])
        for vec in data["cases"]
    ]


@pytest.mark.parametrize("state,block,expected", _load_preassignment_cases())
def test_apply_preassignments_golden_parity(state, block, expected):
    assert apply_preassignments(state, block) == expected


def _load_range_assignment_cases():
    data = json.loads((GOLDEN_DIR / "range-assignment.json").read_text(encoding="utf-8"))
    return [
        pytest.param(vec["input"][0], vec["input"][1], vec["input"][2], vec["output"], id=vec["name"])
        for vec in data["cases"]
    ]


@pytest.mark.parametrize("state,block,args,expected", _load_range_assignment_cases())
def test_apply_range_assignment_golden_parity(state, block, args, expected):
    assert apply_range_assignment(state, block, args) == expected


def _load_outpatient_session_cases():
    data = json.loads((GOLDEN_DIR / "outpatient-session.json").read_text(encoding="utf-8"))
    return [
        pytest.param(vec["input"][0], vec["input"][1], vec["output"], id=vec["name"])
        for vec in data["cases"]
    ]


@pytest.mark.parametrize("state,input_,expected", _load_outpatient_session_cases())
def test_schedule_outpatient_session_golden_parity(state, input_, expected):
    assert schedule_outpatient_session(state, input_) == expected


def _load_daily_report_cases():
    data = json.loads((GOLDEN_DIR / "daily-report.json").read_text(encoding="utf-8"))
    return [
        pytest.param(vec["input"][0], vec["input"][1], vec["output"], id=vec["name"])
        for vec in data["cases"]
    ]


@pytest.mark.parametrize("state,date,expected", _load_daily_report_cases())
def test_generate_daily_report_golden_parity(state, date, expected):
    assert generate_daily_report(state, date) == expected
